SRC += \
   src/ext/meow/meow_init.cpp\
   src/ext/meow/meowCmd.cpp\
   src/ext/meow/meowConstruct.cpp\
   src/ext/meow/meowSEC.cpp\
   src/ext/meow/charGraph.cpp\
   src/ext/meow/meowWord.cpp\
   src/ext/meow/wordGraph.cpp\
   src/aig/gia/giaQbf.c\
   src/ext/meow/meowTrans.cpp\
   src/ext/meow/meowMux.cpp\
   src/ext/meow/meowBound.cpp\
   src/ext/meow/meowBound2.cpp\
   src/ext/meow/meowCNN.cpp\
   src/ext/meow/meowDGSyn.cpp\
   src/ext/meow/meowDG.cpp\
   src/ext/meow/meowDGNode.cpp\
   src/ext/meow/meowDGTrans.cpp\
   src/ext/meow/meowAIG.cpp\
   src/aig/gia/giaBidec.c\
   src/opt/dar/darLib.c
